server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:9090
          predicates:
            - Path=/patients/**
          filters:
            - StripPrefix=0
        - id: notes-service
          uri: http://localhost:9091
          predicates:
            - Path=/notes/**
          filters:
            - StripPrefix=0
        - id: evaluation-service
          uri: http://localhost:9092
          predicates:
            - Path=/assess/**
          filters:
            - StripPrefix=0